steps:
  - name: node:12
    entrypoint: yarn
    args: ["run", "deploy"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "appengine.yaml"]

timeout: "1800s"
images: ["gcr.io/$PROJECT_ID/server-build:$BUILD_ID"]
